title: Tabula Pyrenaei
email: pyrenaeus@gmail.com
description: Atlas historico de los Pirineos en la Antiguedad.
url: "https://tabulapyrenaei.eu"
baseurl: ""
lang: es
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - _posts/markers-part1.html
  - _posts/markers-part2.html
  - _posts/markers-part3.html
  - _posts/markers-part4.html
  - _posts/markers-part5.html
